### ISSUE TITLE
Docstrings for four functions

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/pyBrokk#1]
- [x] Function that creates identifier using text extraction from url @mikeguron 
- [x] Extracts raw text from url optional (filtered by class provided by user) @DMerigo 
- [x] Converts raw text dataframe to bag of words @mehdi-naji 
- [x] Allows you to record the counts of a specific list of words @elenagan

**Comment by mikeguron** [comment]
I have created a python script for the first function and added the docstring to the file.  Can one of you please review and merge the pull request when you have a chance?
